#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak_Ziyaret
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Emlak_Sitesi")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTablo_Gorseller(Tablo_Gorseller instance);
    partial void UpdateTablo_Gorseller(Tablo_Gorseller instance);
    partial void DeleteTablo_Gorseller(Tablo_Gorseller instance);
    partial void InsertTablo_ilan(Tablo_ilan instance);
    partial void UpdateTablo_ilan(Tablo_ilan instance);
    partial void DeleteTablo_ilan(Tablo_ilan instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Emlak_Ziyaret.Properties.Settings.Default.Emlak_SitesiConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tablo_Gorseller> Tablo_Gorseller
		{
			get
			{
				return this.GetTable<Tablo_Gorseller>();
			}
		}
		
		public System.Data.Linq.Table<Tablo_ilan> Tablo_ilan
		{
			get
			{
				return this.GetTable<Tablo_ilan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tablo_Gorseller")]
	public partial class Tablo_Gorseller : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _f_Record;
		
		private System.Nullable<int> _Ilan_No;
		
		private System.Data.Linq.Binary _Gorsel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onf_RecordChanging(int value);
    partial void Onf_RecordChanged();
    partial void OnIlan_NoChanging(System.Nullable<int> value);
    partial void OnIlan_NoChanged();
    partial void OnGorselChanging(System.Data.Linq.Binary value);
    partial void OnGorselChanged();
    #endregion
		
		public Tablo_Gorseller()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_Record", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int f_Record
		{
			get
			{
				return this._f_Record;
			}
			set
			{
				if ((this._f_Record != value))
				{
					this.Onf_RecordChanging(value);
					this.SendPropertyChanging();
					this._f_Record = value;
					this.SendPropertyChanged("f_Record");
					this.Onf_RecordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilan_No", DbType="Int")]
		public System.Nullable<int> Ilan_No
		{
			get
			{
				return this._Ilan_No;
			}
			set
			{
				if ((this._Ilan_No != value))
				{
					this.OnIlan_NoChanging(value);
					this.SendPropertyChanging();
					this._Ilan_No = value;
					this.SendPropertyChanged("Ilan_No");
					this.OnIlan_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gorsel", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Gorsel
		{
			get
			{
				return this._Gorsel;
			}
			set
			{
				if ((this._Gorsel != value))
				{
					this.OnGorselChanging(value);
					this.SendPropertyChanging();
					this._Gorsel = value;
					this.SendPropertyChanged("Gorsel");
					this.OnGorselChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tablo_ilan")]
	public partial class Tablo_ilan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _E_Kayit;
		
		private string _Ilan_Baslik;
		
		private System.Nullable<System.DateTime> _Ilan_Tarihi;
		
		private string _Konum;
		
		private System.Data.Linq.Binary _Ilan_Temel_Gorsel;
		
		private System.Nullable<decimal> _Ucret;
		
		private string _Alan;
		
		private string _Bina_Yasi;
		
		private string _Kat_Sayisi;
		
		private string _Isıtma;
		
		private string _Balkon;
		
		private System.Nullable<decimal> _Aidat;
		
		private string _Ilan_Veren;
		
		private string _Ilan_Veren_Telefon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnE_KayitChanging(int value);
    partial void OnE_KayitChanged();
    partial void OnIlan_BaslikChanging(string value);
    partial void OnIlan_BaslikChanged();
    partial void OnIlan_TarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnIlan_TarihiChanged();
    partial void OnKonumChanging(string value);
    partial void OnKonumChanged();
    partial void OnIlan_Temel_GorselChanging(System.Data.Linq.Binary value);
    partial void OnIlan_Temel_GorselChanged();
    partial void OnUcretChanging(System.Nullable<decimal> value);
    partial void OnUcretChanged();
    partial void OnAlanChanging(string value);
    partial void OnAlanChanged();
    partial void OnBina_YasiChanging(string value);
    partial void OnBina_YasiChanged();
    partial void OnKat_SayisiChanging(string value);
    partial void OnKat_SayisiChanged();
    partial void OnIsıtmaChanging(string value);
    partial void OnIsıtmaChanged();
    partial void OnBalkonChanging(string value);
    partial void OnBalkonChanged();
    partial void OnAidatChanging(System.Nullable<decimal> value);
    partial void OnAidatChanged();
    partial void OnIlan_VerenChanging(string value);
    partial void OnIlan_VerenChanged();
    partial void OnIlan_Veren_TelefonChanging(string value);
    partial void OnIlan_Veren_TelefonChanged();
    #endregion
		
		public Tablo_ilan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_Kayit", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int E_Kayit
		{
			get
			{
				return this._E_Kayit;
			}
			set
			{
				if ((this._E_Kayit != value))
				{
					this.OnE_KayitChanging(value);
					this.SendPropertyChanging();
					this._E_Kayit = value;
					this.SendPropertyChanged("E_Kayit");
					this.OnE_KayitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilan_Baslik", DbType="NVarChar(250)")]
		public string Ilan_Baslik
		{
			get
			{
				return this._Ilan_Baslik;
			}
			set
			{
				if ((this._Ilan_Baslik != value))
				{
					this.OnIlan_BaslikChanging(value);
					this.SendPropertyChanging();
					this._Ilan_Baslik = value;
					this.SendPropertyChanged("Ilan_Baslik");
					this.OnIlan_BaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilan_Tarihi", DbType="Date")]
		public System.Nullable<System.DateTime> Ilan_Tarihi
		{
			get
			{
				return this._Ilan_Tarihi;
			}
			set
			{
				if ((this._Ilan_Tarihi != value))
				{
					this.OnIlan_TarihiChanging(value);
					this.SendPropertyChanging();
					this._Ilan_Tarihi = value;
					this.SendPropertyChanged("Ilan_Tarihi");
					this.OnIlan_TarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Konum", DbType="NVarChar(250)")]
		public string Konum
		{
			get
			{
				return this._Konum;
			}
			set
			{
				if ((this._Konum != value))
				{
					this.OnKonumChanging(value);
					this.SendPropertyChanging();
					this._Konum = value;
					this.SendPropertyChanged("Konum");
					this.OnKonumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilan_Temel_Gorsel", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Ilan_Temel_Gorsel
		{
			get
			{
				return this._Ilan_Temel_Gorsel;
			}
			set
			{
				if ((this._Ilan_Temel_Gorsel != value))
				{
					this.OnIlan_Temel_GorselChanging(value);
					this.SendPropertyChanging();
					this._Ilan_Temel_Gorsel = value;
					this.SendPropertyChanged("Ilan_Temel_Gorsel");
					this.OnIlan_Temel_GorselChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ucret", DbType="Money")]
		public System.Nullable<decimal> Ucret
		{
			get
			{
				return this._Ucret;
			}
			set
			{
				if ((this._Ucret != value))
				{
					this.OnUcretChanging(value);
					this.SendPropertyChanging();
					this._Ucret = value;
					this.SendPropertyChanged("Ucret");
					this.OnUcretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alan", DbType="NVarChar(100)")]
		public string Alan
		{
			get
			{
				return this._Alan;
			}
			set
			{
				if ((this._Alan != value))
				{
					this.OnAlanChanging(value);
					this.SendPropertyChanging();
					this._Alan = value;
					this.SendPropertyChanged("Alan");
					this.OnAlanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bina_Yasi", DbType="NVarChar(150)")]
		public string Bina_Yasi
		{
			get
			{
				return this._Bina_Yasi;
			}
			set
			{
				if ((this._Bina_Yasi != value))
				{
					this.OnBina_YasiChanging(value);
					this.SendPropertyChanging();
					this._Bina_Yasi = value;
					this.SendPropertyChanged("Bina_Yasi");
					this.OnBina_YasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kat_Sayisi", DbType="NVarChar(20)")]
		public string Kat_Sayisi
		{
			get
			{
				return this._Kat_Sayisi;
			}
			set
			{
				if ((this._Kat_Sayisi != value))
				{
					this.OnKat_SayisiChanging(value);
					this.SendPropertyChanging();
					this._Kat_Sayisi = value;
					this.SendPropertyChanged("Kat_Sayisi");
					this.OnKat_SayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isıtma", DbType="NVarChar(20)")]
		public string Isıtma
		{
			get
			{
				return this._Isıtma;
			}
			set
			{
				if ((this._Isıtma != value))
				{
					this.OnIsıtmaChanging(value);
					this.SendPropertyChanging();
					this._Isıtma = value;
					this.SendPropertyChanged("Isıtma");
					this.OnIsıtmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balkon", DbType="NVarChar(20)")]
		public string Balkon
		{
			get
			{
				return this._Balkon;
			}
			set
			{
				if ((this._Balkon != value))
				{
					this.OnBalkonChanging(value);
					this.SendPropertyChanging();
					this._Balkon = value;
					this.SendPropertyChanged("Balkon");
					this.OnBalkonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aidat", DbType="Money")]
		public System.Nullable<decimal> Aidat
		{
			get
			{
				return this._Aidat;
			}
			set
			{
				if ((this._Aidat != value))
				{
					this.OnAidatChanging(value);
					this.SendPropertyChanging();
					this._Aidat = value;
					this.SendPropertyChanged("Aidat");
					this.OnAidatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilan_Veren", DbType="NVarChar(200)")]
		public string Ilan_Veren
		{
			get
			{
				return this._Ilan_Veren;
			}
			set
			{
				if ((this._Ilan_Veren != value))
				{
					this.OnIlan_VerenChanging(value);
					this.SendPropertyChanging();
					this._Ilan_Veren = value;
					this.SendPropertyChanged("Ilan_Veren");
					this.OnIlan_VerenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilan_Veren_Telefon", DbType="NVarChar(25)")]
		public string Ilan_Veren_Telefon
		{
			get
			{
				return this._Ilan_Veren_Telefon;
			}
			set
			{
				if ((this._Ilan_Veren_Telefon != value))
				{
					this.OnIlan_Veren_TelefonChanging(value);
					this.SendPropertyChanging();
					this._Ilan_Veren_Telefon = value;
					this.SendPropertyChanged("Ilan_Veren_Telefon");
					this.OnIlan_Veren_TelefonChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
